import { DeveloperData } from './types';

// These data should be registered by the developers themselves
export const sampleRegisteredDeveloperData = {
  developerId: '001',
  name: 'feng yang',
  standoutIntro: 'Experienced in various of client projects',
  mainProgrammingLanguage: 'javascript',
  githubUrl: 'https://github.com/Finns841594',
  linkedinUrl: 'https://www.linkedin.com/in/feng-yang-511361166/',
  selectedProjectUrls: [
    'https://github.com/Finns841594/moboga',
    'https://github.com/lups-tech/jobMatches',
  ],
  backgroundInformations: {
    nationalities: ['Chinese'],
    spokenLanguages: ['Chinese', 'English', 'Swedish'],
    educations: ['Architecture'],
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Node.js',
      'Express',
      'MongoDB',
    ],
  },
};

// These data should be fetched/generated by the server
export const sampleGeneratedDeveloperData = {
  developerId: '001',
  name: 'feng yang',
  standoutIntro: 'Experienced in various of client projects',
  mainProgrammingLanguage: 'javascript',
  githubUrl: 'https://github.com/Finns841594',
  linkedinUrl: 'https://www.linkedin.com/in/feng-yang-511361166/',
  backgroundInformations: {
    nationalities: ['Chinese'],
    spokenLanguages: ['Chinese', 'English', 'Swedish'],
    educations: ['Architecture'],
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Node.js',
      'Express',
      'MongoDB',
    ],
  },
  // below are generated datas
  githubUserName: 'Finns841594',
  githubProfilePictureUrl:
    'https://avatars.githubusercontent.com/u/65496134?v=4',
  selectedProjects: [],
  commitsCount: 500,
  issuesCount: 100,
} as DeveloperData;
